/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_denachina_shieldsdk_utils_FilterCPlusUtils */

#ifndef _Included_com_denachina_shieldsdk_utils_FilterCPlusUtils
#define _Included_com_denachina_shieldsdk_utils_FilterCPlusUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_denachina_shieldsdk_utils_FilterCPlusUtils
 * Method:    addSensitiveWord
 * Signature: (Ljava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_com_denachina_shieldsdk_utils_FilterCPlusUtils_addSensitiveWord
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_denachina_shieldsdk_utils_FilterCPlusUtils
 * Method:    replaceSensitiveWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_denachina_shieldsdk_utils_FilterCPlusUtils_replaceSensitiveWord
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
